# Generated by Django 3.1.5 on 2021-02-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
