# Generated by Django 3.1.5 on 2021-03-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_types'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='types',
            new_name='student_type',
        ),
    ]
