# Generated by Django 3.1.5 on 2021-03-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auto_20210304_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='Department',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Batch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Type',
            field=models.CharField(max_length=50),
        ),
    ]
