# Generated by Django 3.1.5 on 2021-03-08 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_auto_20210305_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_type',
            old_name='name',
            new_name='Name',
        ),
    ]
