# Generated by Django 3.1.5 on 2021-03-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_auto_20210308_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=10, unique=True)),
                ('courseTitle', models.CharField(max_length=10)),
                ('courseDescription', models.TextField()),
            ],
        ),
    ]
