# Generated by Django 3.1.5 on 2021-03-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseType',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
