# Generated by Django 3.1.5 on 2021-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseseats',
            name='seats_allocated',
            field=models.IntegerField(default=None),
        ),
    ]
