# Generated by Django 3.1.5 on 2021-03-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_courseseats_seats_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseBatch',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='studentType',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
