# Generated by Django 3.1.5 on 2021-03-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_auto_20210309_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='seats_opted',
            field=models.IntegerField(default=0),
        ),
    ]
