# Generated by Django 3.1.5 on 2021-03-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_auto_20210309_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courseSeats',
        ),
    ]
