# Generated by Django 3.1.5 on 2021-03-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_delete_courseseats'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seats_avail',
            field=models.IntegerField(default=0),
        ),
    ]
