# Generated by Django 3.1.5 on 2021-03-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_course_seats_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='LS',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='NME',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='PART1',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
