# Generated by Django 3.1.5 on 2021-03-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_auto_20210309_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_detail',
            name='LS',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='NME',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='PART1',
        ),
    ]
