# Generated by Django 3.1.5 on 2021-03-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_auto_20210309_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_detail',
            name='mobile',
        ),
        migrations.AddField(
            model_name='admin_detail',
            name='email',
            field=models.EmailField(default=None, max_length=125),
            preserve_default=False,
        ),
    ]
