# Generated by Django 3.1.5 on 2021-03-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_auto_20210314_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_detail',
            name='email',
            field=models.EmailField(default='narmatha14amc@gmail.com', max_length=125),
        ),
    ]
