# Generated by Django 3.1.5 on 2021-03-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0024_students_std_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seats_avail',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seats_opted',
        ),
        migrations.RemoveField(
            model_name='course',
            name='studentType',
        ),
        migrations.AddField(
            model_name='course',
            name='deps',
            field=models.ManyToManyField(to='Admin.departments'),
        ),
        migrations.AddField(
            model_name='course',
            name='std_types',
            field=models.ManyToManyField(to='Admin.student_type'),
        ),
    ]
