# Generated by Django 3.1.5 on 2021-03-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0026_remove_course_coursedescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='cDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('_data', models.TextField(blank=True, db_column='data')),
            ],
        ),
    ]
