# Generated by Django 3.1.5 on 2021-03-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0027_cdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdetails',
            name='_data',
        ),
        migrations.AddField(
            model_name='cdetails',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='adDetails',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Admin.cdetails'),
        ),
    ]
