# Generated by Django 3.1.5 on 2021-03-16 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0029_remove_course_addetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdetails',
            name='cs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.course'),
            preserve_default=False,
        ),
    ]
