# Generated by Django 3.1.5 on 2021-03-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0030_cdetails_cs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cDetails',
        ),
    ]
