# Generated by Django 3.1.5 on 2021-03-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0031_delete_cdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='cDetails1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.course')),
            ],
        ),
    ]
