# Generated by Django 3.1.5 on 2021-03-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0032_cdetails1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdetails1',
            name='cs',
            field=models.CharField(max_length=50),
        ),
    ]
