# Generated by Django 3.1.5 on 2021-03-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0033_auto_20210316_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_detail',
            new_name='custom_admin',
        ),
    ]
