# Generated by Django 3.1.5 on 2021-03-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0035_auto_20210316_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdetails1',
            name='img',
        ),
        migrations.AddField(
            model_name='cdetails1',
            name='_data',
            field=models.TextField(blank=True, db_column='data'),
        ),
    ]
