# Generated by Django 3.1.5 on 2021-03-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0036_auto_20210316_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cDetails1',
            new_name='cDetails',
        ),
    ]
