# Generated by Django 3.1.5 on 2021-03-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0037_auto_20210316_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdetails',
            name='_data',
        ),
        migrations.AddField(
            model_name='cdetails',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
