# Generated by Django 3.1.5 on 2021-03-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0038_auto_20210317_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_admin',
            name='otpExpires',
            field=models.DateTimeField(default=None),
        ),
    ]
