# Generated by Django 3.1.5 on 2021-03-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0039_custom_admin_otpexpires'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_admin',
            name='otp',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
