# Generated by Django 3.1.5 on 2021-03-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0041_course_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_admin',
            name='otpExpires',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
