# Generated by Django 3.1.5 on 2021-03-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0042_auto_20210318_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_admin',
            name='otp',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
